# Generated by Django 5.1.6 on 2025-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='', upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
