# Generated by Django 5.1.6 on 2025-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_category_productmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/images'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.CharField(max_length=50),
        ),
    ]
